name: terminator
adopt-info: terminator
summary: Multiple GNOME terminals in one window
description: |
  Create more terminals by:

  horizontal split: Ctrl-Shift-o
  vertical split: Ctrl-Shift-e
  Shift focus to:
  
  next terminal: Ctrl-Shift-n
  previous terminal: Ctrl-Shift-p
  New tab: Ctrl-Shift-t

  New window: Ctrl-Shift-i

  Close terminal or tab:

  Ctrl-Shift-w
  or right mouse click -> Close
  Close window with all it's terminals and tabs: Ctrl-Shift-q

  Reset zoom: Ctrl-0

  Terminator Preferences menu:

  right mouse click -> Preferences
  These and more modifiable shortcuts in:

  right mouse click -> Preferences -> Keybindings tab
  Web Documentation:

  press F1 or at https://gnome-terminator.readthedocs.io/en/latest/
  More info about shortcuts and cli config in man pages:

  man terminator
  man terminator_config
  
base: core20
grade: stable
confinement: classic
compression: lzo

license: GPL-2.0

apps: 
  terminator:
    command: bin/terminator
    extensions:
      - gnome-3-38 
      
parts:
  terminator:
    source: https://github.com/gnome-terminator/terminator
    source-type: git
    plugin: python
        
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//')"
    
    build-packages:
      - python3-gi 
      - python3-gi-cairo 
      - python3-psutil 
      - python3-configobj
      - gir1.2-keybinder-3.0 
      - gir1.2-vte-2.91 
      - gettext 
      - intltool 
      - dbus-x11 
      
    stage-packages:
      - python3-gi 
      - python3-gi-cairo 
      - python3-psutil 
      - python3-configobj
      - gir1.2-keybinder-3.0 
      - gir1.2-vte-2.91 
      - gettext 
      - intltool 
      - dbus-x11     
